/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_final_classes;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.event.EventHandler;

import java.util.Arrays;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.RadioButton;
import javafx.scene.control.SelectionMode;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleGroup;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) {
      // Set Window title
      stage.setTitle("Pizza Cataloger");
      
      // Grid
      GridPane grid = new GridPane();
      ColumnConstraints column1 = new ColumnConstraints(100,100,Double.MAX_VALUE);
      ColumnConstraints column2 = new ColumnConstraints(100);
      grid.getColumnConstraints().addAll(column1, column2);
      grid.setTranslateX(20);
      grid.setTranslateY(20);

      //Pizza name input
      TextField nameField = new TextField();
      grid.addRow(0, new Label("Name of Pizza: "), nameField);
      
      //Pizza toppings input
      ListView<String> listView = new ListView<String>();
      ObservableList<String> list = FXCollections.observableArrayList();
      listView.setItems(list);
      list.addAll( Arrays.stream(Topping.values()).map(Enum::name).toArray(String[]::new) );
      listView.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
      listView.setOnMouseClicked(new EventHandler<Event>() {
        @Override
        public void handle(Event event) {
            ObservableList<String> selectedItems =  listView.getSelectionModel().getSelectedItems();
            for(String s : selectedItems){
                System.out.println("selected item " + s);
            }
        }

    });
      grid.addRow(1, new Label("Toppings: "), listView);

      //set the scene
      var scene = new Scene(new StackPane(grid), 640, 480);
      stage.setScene(scene);
      stage.show();
    }

    public static void main(String[] args) {
      //PizzaDB db = new PizzaDB("pizza.dat");
      //Pizza ian = new Pizza(Size.L);
      //db.addPizza(ian);
      //System.out.println(ian.size+"("+ian.size.getInches()+")");
      //System.out.println( "Pizzas: " + db.getPizzas().get(0).size.getInches() );
      launch();
    }
}
